homepage:
    pattern:  /
    defaults: { _controller: GarethBundle:Default:index }
projects:
    pattern:  /projects
    defaults: { _controller: GarethBundle:Project:index }
project_create:
    pattern:  /projects/create
    defaults: { _controller: GarethBundle:Project:create }
project:
    pattern:  /projects/{name}
    defaults: { _controller: GarethBundle:Project:show }
    requirements:
        name: ".+"

login:
    pattern:   /login
    defaults:  { _controller: GarethBundle:Security:login }
login_check:
    pattern:   /login_check
logout:
    pattern:   /logout

settings:
    pattern:   /settings
    defaults:  { _controller: GarethBundle:Settings:profile }
identities:
    pattern:   /settings/identities
    defaults:  { _controller: GarethBundle:Settings:identities }
my_remotes:
    pattern:   /settings/remotes
    defaults:  { _controller: GarethBundle:Settings:remotes }