parameters:
#    gareth.example.class: Gareth\GarethWebBundle\Example

services:
#    gareth.example:
#        class: %gareth.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
