security:
    encoders:
        Gareth\GarethWebBundle\Entity\User:
            algorithm:   whirlpool
            iterations:  10000

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_PROJECT_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: GarethBundle:User, property: username }

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login: ~
            logout:       true
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
